=== RahulRao333/lab-3/inv_validator.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
</xs:schema>

<xs:element name="inventory-management">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="storage" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pid" type="xs:int"/>
                            <xs:element name="pname" type="xs:string"/>
                            <xs:element name="p_postion" type="xs:string"/>
                            <xs:element name="q_instock" type="xs:int"/>


                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
                <xs:element name="vendor" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="phoneno" type="xs:long"/>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="name" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
                <xs:element name="products" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pquantity">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="100"/>

                                    </xs:restriction>

                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pname" type="xs:string"/>
                            <xs:element name="pid" type="xs:int"/>
                            
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
    
</xs:schema>

=== RahulRao333/lab-3/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="inv_style.xsl" type="text/xsl"?>
<inventory-management xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inv_validator.xsd">

    <storage>
        <pid>1</pid>
        <pname>oil</pname>
        <p_postion>cr</p_postion>
        <q_instock>52</q_instock>

    </storage>
    <storage>
        <pid>2</pid>
        <pname>break_pad</pname>
        <p_postion>cr</p_postion>
        <q_instock>53</q_instock>

    </storage>
    
    <vendor>
        <phoneno>9802123</phoneno>
        <id>6</id>
        <name>rahul rao</name>
    </vendor>
    <vendor>
        <phoneno>98028971</phoneno>
        <id>7</id>
        <name>sharath</name>
    </vendor>
    
    <products>
        <pquantity>50</pquantity>
        <pname>spanner</pname>
        <pid>55</pid>
    </products>
    
</inventory-management>
